title: Minimal theme
logo: /assets/img/Hemanth.jpg
description:
  <p align="center">
  <a href="/assets/img/Hemanth Kumar Resume.doc">Resume</a> |
  <a href="https://www.linkedin.com/in/hemanth-kumar-08b5a827/">LinkedIn</a> |
  <a href="https://github.com/hemanth987kumar">GitHub</a>

theme: jekyll-theme-minimal
